### ISSUE TITLE
Python 3.10 Support

### ISSUE THREAD

**Issue by MiddleMan5** [SupImDos/pydantic-argparse#3]
I noticed the package restricts installation to python3.9 exclusively, are there any known compatibility problems with other versions?

**Comment by SupImDos** [comment]
Hi @MiddleMan5,

Thanks very much for raising this issue :blush:

I believe when I initially created this package, I restricted it to `python-3.9` as `python-3.10` was still in development, and I wasn't sure if it would eventually be compatible - there is still ongoing development regarding various parts of the type system.

There is definitely a large incompatibility with `python-3.8` and below, due to this package using the builtin types as generics (see: https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections). I'm not sure this package will ever support `<3.9`, unless a serious effort is undertaken (even then I'm not sure if its worth it).

Anyway, regarding `python-3.10`, I don't believe there are currently any specific incompatibilities with `3.10` - as all linting, static type checking and unit tests seem to pass in `3.10`. There may exist some underlying issues with the `pydantic` package itself in `3.10` (e.g. https://github.com/samuelcolvin/pydantic/issues/3300), but I don't think this should deter this package's support for it.

I'll try and push a `v0.3.0` update as soon as I can with support for `python-3.10`, once I confirm compatibility 😄

SupImDos

**Comment by SupImDos** [comment]
Released `v0.3.0` on PyPI targeting Python `^3.9`, i.e. Python >=3.9, <4.0.
Link: https://pypi.org/project/pydantic-argparse/0.3.0/

**Comment by MiddleMan5** [comment]
Thanks for the quick turnaround! I just checked the new package with our app and installation works!
